# Generated by Django 2.0 on 2019-02-28 14:25

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='content'),
        ),
    ]
