# Generated by Django 2.0.2 on 2019-03-02 07:20

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190228_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True),
        ),
    ]
