# Generated by Django 2.0.2 on 2019-03-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20190311_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='patent',
            new_name='parent',
        ),
    ]
